version: '3.7'

services:
  lavagna_app:
    image: fat_image:1.0
    container_name: lavagna_app
    networks:
      - postgres_net
    restart: always
    ports:
      - "8080:8080"
    entrypoint: java -Xms64m -Xmx128m -Ddatasource.dialect=PGSQL -Ddatasource.url=jdbc:postgresql://localhost:5432/lavagna -Ddatasource.username=adam -Ddatasource.password=password -Dspring.profiles.active=dev -jar /usr/src/target/lavagna-jetty-console.war
    depends_on:
      - lavagna_database
  lavagna_database:
    image: postgres:13.8
    container_name: lavagna_database
    environment:
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lavagna
    # command: su -u adam initdb /data/application/init.sql
    volumes:
      - ./lavagna_data:/var/lib/postgresql/lavagna
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # entrypoint: ["pg_ctl", "-D", "/var/lib/postgresql/data", "-l", "logfile start"]
    networks:
      - postgres_net
    restart: always
    ports:
     - "5432:5432"
    # healthcheck:
    #   test: curl http://localhost:5432
    #   interval: 3s
    #   retries: 8
    #   start_period: 5s
    #   timeout: 5s

volumes:
  lavagna_data:
    driver: local

networks:
  postgres_net:
    driver: bridge