version: '3.7'

services:
  lavagna_app:
    image: fat_image:1.0
    container_name: lavagna_app
    networks:
      - mysql_net
    restart: always
    ports:
      - "8080:8080"
    entrypoint: java -Xms64m -Xmx128m -Ddatasource.dialect=MYSQL -Ddatasource.url=jdbc:mysql://lavagna_database:3306/lavagna?useUnicode=true&characterEncoding=utf-8&useSSL=false -Ddatasource.username=root -Ddatasource.password=password -Dspring.profiles.active=dev -jar /usr/src/target/lavagna-jetty-console.war
    depends_on:
      lavagna_database:
        condition: service_healthy
  lavagna_database:
    image: mysql:5.7
    container_name: lavagna_database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lavagna
    # command: --init-file /data/application/init.sql
    volumes:
      - lavagna_data:/var/lib/mysql
      # - ./lavagna.sql:/data/application/init.sql
    networks:
      - mysql_net
    restart: always
    ports:
     - "3306:3306"
    healthcheck:
      test: curl --fail http://localhost:3306
      interval: 3s
      retries: 20
      start_period: 5s
      timeout: 5s

volumes:
  lavagna_data:
    driver: local

networks:
  mysql_net:
    driver: bridge